version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"  # Mapeie para 8080 externamente
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - noaa_ana_net
    restart: unless-stopped

networks:
  noaa_ana_net:
    external: true
